openapi: 3.0.1
info:
  version: 1.0.0
  title: TED
  description: >-
    Realize transferencias de valores através do canal de pagamentos TED. Consulte também
    nossa [documentação](https://bankly.readme.io/v1.0/docs/) para mais detalhes
    sobre os fluxos de negócio.
servers:
  - url: 'https://api.sandbox.bankly.com.br'

paths:
  /fund-transfers/{authenticationCode}:
    get:
  /fund-transfers:
    get:
    post:

security:
  - Bearer: []
components:
  parameters:
    ApiVersion:
      name: api-version
      in: header
      description: |
        Versão da API. 
        _Atualmente estamos na **1.0**._
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: 1
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      description: Chave de idempotêcia para a requisição (uuid v4).
      required: false
      style: simple
      explode: false
      schema:
        type: string
  schemas:
    Error:
      type: object
      properties:
        code:
          description: Código do erro.
          type: string
          nullable: true
        propertyName:
          description: >-
            Parametro ou propriedade com problema. Somente será retornado quando
            o erro for de sintaxe (Bad Request).
          type: string
          nullable: true
        messages:
          description: Lista de descrições do problema encontrado.
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
    ErrorResponse:
      description: Detalhes do erro identificado.
      type: object
      properties:
        errors:
          description: Lista de erros identificados. Trate-os antes de tentar novamente.
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Error'
        reference:
          type: integer
          format: int32
      additionalProperties: false
  headers:
    CorrelationId:
      description: Id correlação da operação requisitada.
      style: simple
      explode: false
      schema:
        type: string
    Location:
      description: Localização do recurso recém-criado ou em análise.
      style: simple
      explode: false
      schema:
        type: string
  responses:
    '202':
      description: |
        Requisição foi aceita e está sendo processada.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
        Location:
          $ref: '#/components/headers/Location'
    '400':
      description: |
        Há algum problema com a sua requisição.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/invalidParameterErrorResponse'
    '403':
      description: |
        O acesso ao recurso foi negado pelo servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
    '404':
      description: |
        Recurso não encontrado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
    '409':
      description: >
        A solicitação conflitou com o estado atual do recurso existente no
        servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '422':
      description: >
        A sintaxe da requisição esta correta, mas não foi possível processar
        devido uma regra de negócio.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '500':
      description: |
        Ocorreu algum erro inexperado no nosso servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
      bearerFormat: JWT
  examples:
    invalidParameterErrorResponse:
      value:
        errors:
          - code: INVALID_PARAMETER
            propertyName: '{{propertyName}}'
            messages:
              - '{{"propertyName" error message}}'
      summary: Parametro inválido
    errorResponse:
      value:
        errors:
          - code: SOME_ERROR_CODE
            messages:
              - '{{Some error message}}'
      summary: Erro de negócio
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
