openapi: 3.0.3

info:
  title: Exemplos reutilizáveis para todas as APIs.
  version: '1.0'

paths: {}

components:
  
  examples:

    invalidParameterErrorResponse:
      value:
        errors:
          - code: INVALID_PARAMETER
            propertyName: '{{propertyName}}'
            messages:
              - '{{"propertyName" error message}}'
      summary: Parametro inválido

    errorResponse:
      value:
        errors:
          - code: SOME_ERROR_CODE
            messages:
              - '{{Some error message}}'
      summary: Erro de negócio

