openapi: 3.0.1
info:
  version: 1.0.0
  title: Gestão de cartões
  description: Solicite e gerencie cartões vinculados à conta do seu cliente em poucos minutos. Consulte também nossa [documentação](https://bankly.readme.io/v1.0/docs/) para mais detalhes sobre os fluxos de negócio.

servers:
  - url: https://api.sandbox.bankly.com.br

paths: {}

security:
  - Bearer: []

components: {}
  
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl