openapi: 3.0.1
info:
  version: 1.0.0
  title: Boletos
  description: >-
    Faça pagamentos de contas e convênios de forma simples e segura. Consulte também
    nossa [documentação](https://bankly.readme.io/v1.0/docs/) para mais detalhes
    sobre os fluxos de negócio.
servers:
  - url: 'https://api.sandbox.bankly.com.br'

paths: {}

security:
  - Bearer: []

components: {}
  
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl