name: Sync OAS to ReadMe
on:
  push:
    branches:
      - ted
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './api/v1/pix/schema.yaml'
          # api-version: 'v1.0.0'
